### PR TITLE
support getting QueueName via Fn::GetAtt refs

### PR DESCRIPTION
**Pull request by YOU54F**
Hey @poupougnac,

Great plugin thanks,

Is it possible to add this functionality, to work nicely with cloudformation attributes.

I've published and tested the changes here `@you54f/serverless-offline-sqs-dlq`

### CODE REVIEW

**Comment by pmaoui** [comment]
Hello @YOU54F, thank you for your contribution. 
I've added some eslint/prettier rules based on [serverless-offline](https://github.com/dherault/serverless-offline/).
Could you rebase your work based on the new `master` branch in order for me to publish your work ?
Thank you

**Comment by YOU54F** [comment]
Will do chap, on holiday this week but will jump on it on Monday

**Comment by YOU54F** [comment]
@poupougnac rebased now, need to test it works against my project, will check it out tomorrow during the day

**Comment by racedale** [comment]
@YOU54F @poupougnac any updates on merging this?

**Comment by pmaoui** [comment]
@racedale , I didn't test thoses changes. I will check this and merge it ASAP

**Comment by pmaoui** [comment]
Fix with #3 
I have added many formats on v1.5.0

**Pull request merged**
